name: CI

on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

jobs:
  build:

    runs-on: ubuntu-latest
    # see /dev.Dockerfile
    container: warchantua/py-toml-dev:v1
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: get toml-test
        run: |
            git clone https://github.com/BurntSushi/toml-test
          # cd toml-test/cmd/toml-test
          # go build

      - name: Run python tests
        run: |
            pip -q install "tox>=4"
            tox run-parallel --parallel-no-spinner

      # TODO(warchant): this cmd is old, need to update it
      # - name: Run go tests
      #   run: |
      #       pip -q install setuptools
      #       python setup.py install
      #       ./toml-test/cmd/toml-test/toml-test -i ./tests -g ./tests/gotests.sh
